version: "3.9"

services:
  orders-db:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5435:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
      - ./order-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payments-db:
    image: postgres:16-alpine
    container_name: payments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5436:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data
      - ./payment-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    environment:
      HTTP_PORT: "8081"
      GRPC_PORT: "9091"
      DB_HOST: payments-db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: payments_db
    ports:
      - "8081:8081"
      - "9091:9091"   # gRPC — called by Order Service
    depends_on:
      payments-db:
        condition: service_healthy

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    environment:
      HTTP_PORT: "8080"
      GRPC_PORT: "9090"
      DB_HOST: orders-db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: orders_db
      PAYMENT_SERVICE_GRPC_ADDR: "payment-service:9091"
      PAYMENT_TIMEOUT_SECS: "5"
    ports:
      - "8080:8080"
      - "9090:9090"   # gRPC — for SubscribeToOrderUpdates streaming
    depends_on:
      orders-db:
        condition: service_healthy
      payment-service:
        condition: service_started

volumes:
  orders_data:
  payments_data:
